### ISSUE TITLE
Battery level, set notification interval

### ISSUE THREAD

**Issue by mm108** [zh2x/SpO2-BLE-for-Android#3]
Couple of quick questions

1) Is there a way to read the battery level? I have seen that some of the apps have a battery level indicator too. So has someone managed to decode that?

2) Is it possible to set the notification interval? The default update rate seems to be a bit high for certain applications. Was thinking if there is a way to change the notification interval.

Thanks

**Comment by zh2x** [comment]
As the protocol paper, the oximeters you have can not send out Battery Level, can not change notification.
This is a regular communication protocol to most our customers.
We have other protocols but can not sovle the two issues one time.
If you want a sample protocol, maybe you can consult the salesmen, and send your protocol to our technical support.

**Comment by mm108** [comment]
Sure, thanks for the information. I'll get in touch should this requirement come up again.
